### PR TITLE
Restructuring

### LINKED ISSUE #11: RegionServicesManager fails
MC Versions below 1.15 lack ConfigurationSection#getLocation(String) method
- [x] Patch: disable RSM init for legacy
- [x] **Solution: replace method with custom ConfigurationSerializable class** + delegate

### PR DESCRIPTION
**Pull request by ms5984**
### Main goals
- [x] **Resolve cyclic dependencies and work toward Maven compatibility**
I pulled most of the libraries from the plugin module and moved them to a new "labyrinth-common" module. The main plugin class and its resource (plugin.yml) remain in `labyrinth-plugin`. A new class--`LabyrinthProvider`--exists to manage access to the plugin's functionalities. See `api` package in `labyrinth-common`.
- [x] **~~Try out adventure shade~~** _meh, shelfed for later date_
As mentioned in early commits, I accomplished it but ultimately decided against it for now (it swells the jar for Spigot by almost 1MB). Consider making abstraction(s) that use `adventure` and other libraries provided by Paper, falling back to traditional implementations when on Spigot.
- [x] **Completely remove Vault and Enterprise shade logic**
It was iffy; we didn't really use it. My solution was to completely rework the economy hooks to carefully check plugin presences and only then try to reference classes as local variables (static == blows up).
- [x] **Redesigned `EconomyProvision` service to really be like a service**
Kept static getter; created dedicated `EconomyProvision` implementations which are instantiated by their respective hook classes and registered directly with the Bukkit ServicesManager with priorities (Vault at `Low`, Advanced/Enterprise at `Normal`). Replaced now obsolete `DefaultProvision` with a private static inner, '`EmptyProvision`' class to be returned in the case that no services have registered. Returns empty Optionals.
- [x] **Get repository cleaned up and ready for OSSRH deployment**
Still working on this one; be careful with this commit, you may want to backup your project's `.idea` folder and `Labyrinth.iml` file, pull, close, and then drop them back in. Hopefully this'll help things stay clearer with VCS later.
- [x] **Deployment action .yml**
All set. I still need to add the secrets, but the workflow should be ready.

### CODE REVIEW

**Comment by ms5984** [comment]
Secrets added; should be ready for deployment

**Comment by ms5984** [comment]
- [x] **Added `templates` project as a native resource**

**Review by Hempfest — APPROVED** [review]
As discussed via voice room, things should merge within the same only slight things will need to be updated in plugins like usage of the API and stuff now. Awesome!

**Comment by ms5984** [comment]
Added commit for additional repository (missing alternate Sonatype repo for templates)
https://central.sonatype.org/publish/publish-guide/#deployment

**Comment by ms5984** [comment]
@Hempfest if possible, let's squash+merge this and add your edits in a fresh branch+pr

**Pull request merged**
